joueur_homepage:
    path:     /joueur
    defaults: { _controller: JoueurBundle:Default:index }
joueur_monProfil:
    path:     /monProfil
    defaults: { _controller: JoueurBundle:Default:monProfil }
redirection_apresLogin:
    path:     /redirection
    defaults: { _controller: JoueurBundle:Default:redirection_apresLogin }
joueur_licences:
    path:     /joueur/licences
    defaults: { _controller: JoueurBundle:Default:licences }
joueur_licencesInfos:
    path:     /joueur/licencesInfos/{id}
    defaults: { _controller: JoueurBundle:Default:licencesInfos }
joueur_documents:
    path:     /joueur/documents
    defaults: { _controller: JoueurBundle:Default:documents }
joueur_uploadFile:
    path:     /joueur/uploadFile
    defaults: { _controller: JoueurBundle:Default:uploadFile }
joueur_modifDonneesPerso:
    path:     /joueur/modifDonneesPerso
    defaults: { _controller: JoueurBundle:Default:modifDonneesPerso }
joueur_inscriptionLicenceEtape1:
    path:     /joueur/inscriptionLicenceEtape1/{id}
    defaults: { _controller: JoueurBundle:Default:inscriptionLicenceEtape1 }
joueur_inscriptionLicenceEtape2:
    path:     /joueur/inscriptionLicenceEtape2
    defaults: { _controller: JoueurBundle:Default:inscriptionLicenceEtape2 }


