admin_homepage:
    path:     /admin
    defaults: { _controller: AdminBundle:Default:index }
admin_licences:
    path:     /admin/licences
    defaults: { _controller: AdminBundle:Default:licences }
admin_creerFormLicence:
    path:     /admin/creerFormLicence
    defaults: { _controller: AdminBundle:Default:creerFormLicence }
admin_licenceCreer:
    path:     /admin/licenceCreer
    defaults: { _controller: AdminBundle:Default:licenceCreer }
admin_modifierLicence:
    path:     /admin/modifierLicence/{id}
    defaults: { _controller: AdminBundle:Default:modifierLicence }
admin_licencesNonVisibles:
    path:     /admin/licencesNonVisibles
    defaults: { _controller: AdminBundle:Default:licencesNonVisibles }
admin_uploadFile:
    path:     /admin/uploadFile
    defaults: { _controller: AdminBundle:Default:uploadFile }
admin_gererUploadLicence:
    path:     /admin/gererUploadLicence
    defaults: { _controller: AdminBundle:Default:gererUploadLicence }
admin_supprimerUploadLicence:
    path:     /admin/supprimerUploadLicence/{id}
    defaults: { _controller: AdminBundle:Default:supprimerUploadLicence }
admin_suppressionEnCoursUploadLicence:
    path:     /admin/suppressionEnCoursUploadLicence/{id}
    defaults: { _controller: AdminBundle:Default:suppressionEnCoursUploadLicence }