admin_homepage:
    path:     /admin
    defaults: { _controller: AdminBundle:Default:index }
admin_licences:
    path:     /admin/licences
    defaults: { _controller: AdminBundle:Default:licences }
admin_creerFormLicence:
    path:     /admin/creerFormLicence
    defaults: { _controller: AdminBundle:Default:creerFormLicence }
admin_modifierLicence:
    path:     /admin/modifierLicence/{id}
    defaults: { _controller: AdminBundle:Default:modifierLicence }
admin_licencesNonVisibles:
    path:     /admin/licencesNonVisibles
    defaults: { _controller: AdminBundle:Default:licencesNonVisibles }
admin_gererUploadLicence:
    path:     /admin/gererUploadLicence
    defaults: { _controller: AdminBundle:Default:gererUploadLicence }
admin_supprimerUploadLicence:
    path:     /admin/supprimerUploadLicence/{id}
    defaults: { _controller: AdminBundle:Default:supprimerUploadLicence }
admin_suppressionEnCoursUploadLicence:
    path:     /admin/suppressionEnCoursUploadLicence/{id}
    defaults: { _controller: AdminBundle:Default:suppressionEnCoursUploadLicence }
admin_joueurs:
    path:     /admin/joueurs
    defaults: { _controller: AdminBundle:Default:joueurs }
admin_joueursInfo:
    path:     /admin/joueursInfo/{id}
    defaults: { _controller: AdminBundle:Default:joueursInfo }
admin_licenceInfo:
    path:     /admin/licenceInfo/{id}
    defaults: { _controller: AdminBundle:Default:licenceInfo }
admin_recupLicencieCSV:
    path:     /admin/recupLicencieCSV/export.csv
    defaults: { _controller: AdminBundle:Default:recupLicencieCSV }
admin_recupLicencieParLicenceCSV:
    path:     /admin/recupLicencieParLicenceCSV/export.csv/{licence_id}
    defaults: { _controller: AdminBundle:Default:recupLicencieParLicenceCSV }
    requirements:
        id: \d+