<?php

namespace Joueur\JoueurBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * fichierUploadRepositoryJoueur
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class fichierUploadJoueurRepository extends EntityRepository
{
}
